### ISSUE TITLE
Content height misscalculated

### ISSUE THREAD

**Issue by DiogoDeAlmeida** [the49ltd/The49.Maui.BottomSheet#40]
Hi !

I have a last issue to finish to implement my Bottom Sheets.
Content height seems to be misscalculated when Label take multiple lines and i let him took all place it need. Same issue on iOS and Android side.

If you have any workaround or i miss something ? 

Android :

<img src="https://github.com/the49ltd/The49.Maui.BottomSheet/assets/67577360/135d4f1c-357a-4101-ba8d-e6f6884ecf46" width="100" height="auto">
<img src="https://github.com/the49ltd/The49.Maui.BottomSheet/assets/67577360/f2a7b970-4c8e-4de2-a98e-39fe686da9ed" width="100" height="auto">

iOS : 

<img src="https://github.com/the49ltd/The49.Maui.BottomSheet/assets/67577360/b005a297-8a4e-474c-992c-0c40531f4d4c" width="100" height="auto">
<img src="https://github.com/the49ltd/The49.Maui.BottomSheet/assets/67577360/82383b60-5f59-4413-b99b-aefe7e9beff8" width="100" height="auto">

**Comment by DiogoDeAlmeida** [comment]
I juste tried the last version "1.0.0-rc5".

It seems the Android version work now correctly but i have still the issue on iOS.

**Comment by troy-ob** [comment]
I have the same issue and I think I know what is the cause. I think the content height is calculated before padding-left and padding-right are considered. And because the paddings cause the label to break into lines differently, it miscalculates. You could try to remove the paddings left/right and see how it behaves. However, not having these paddings is not optimal. 

At least that's how it is like on my end with rc-9.

**Comment by paulvarache** [comment]
Hi,

I wasn't sure what this issue was about exactly. I assumed this meant that when using the ContentDetent and the content of the sheet gets resize (e.g. label text changes), the sheet on iOS wasn't adapting to the new size.

I have just pushed a fix for what I just described, it'll be available under rc12. You might nee to manually set this version as nuget doesn't offer updates since rc10.

If this wasn't the issue, let me know in more details the problems you're having

**Comment by troy-ob** [comment]
Hi, 
the issue still persists for me, on Android at least. 

Setup: 
* ContentDetent
* Label with lots of text in the BottomSheet
* rc12

Image1 with BottomSheet Paddings 32, 32, 32, 40
![image](https://github.com/the49ltd/The49.Maui.BottomSheet/assets/134378785/d57b7c5b-1505-4652-bad5-5054895bb00b)

Image2 with BottomSheet Paddings 0, 32, 0, 40
![image](https://github.com/the49ltd/The49.Maui.BottomSheet/assets/134378785/79b920c6-8136-470e-bc77-9bd49d7152e1)

You can see in Image 1 that the BottomPadding is lost (or at least off screen). If I remove the paddings left and right, the BottomPadding is still applied correctly. I think that the BottomSheet-height is calculated before paddings left and right are considered -> content is shifted downwards and partly off screen.

**Comment by paulvarache** [comment]
Thanks, the description helped. I have just updated the package with a fix for this. It is availabel under 1.0.0

@troy-ob As you suspected, the Horizontal padding wasn't removed from the availableWidth when calculating the ContentDetentHeight

Let me know if that solves your issue

**Comment by troy-ob** [comment]
Thanks @paulvarache, that fixed the issue :)
